-- CST438 Project 2
-- Initial Supabase database setup for the Availability Planner API.
--
-- This file documents the database tables, relationships, and initial
-- weekly time-slot data.
--
-- It does not contain passwords, API keys, or other secrets.
-- Spring Boot integration and API routes will be implemented separately.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    oauth_provider text not null,
    oauth_subject text not null,
    display_name text not null,
    role text not null default 'USER',
    created_at timestamptz not null default now(),

    constraint users_role_check
        check (role in ('USER', 'ADMIN')),

    constraint users_oauth_identity_unique
        unique (oauth_provider, oauth_subject)
);

create table if not exists public.schedule_groups (
    id bigint generated by default as identity primary key,
    event_name text not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),

    constraint schedule_groups_created_by_fk
        foreign key (created_by)
        references public.users(id)
        on delete cascade
);

create table if not exists public.group_members (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    user_id bigint not null,
    joined_at timestamptz not null default now(),

    constraint group_members_group_fk
        foreign key (group_id)
        references public.schedule_groups(id)
        on delete cascade,

    constraint group_members_user_fk
        foreign key (user_id)
        references public.users(id)
        on delete cascade,

    constraint group_members_unique
        unique (group_id, user_id)
);

create table if not exists public.time_slots (
    id bigint generated by default as identity primary key,
    day_of_week smallint not null,
    start_hour smallint not null,
    end_hour smallint not null,

    constraint time_slots_day_check
        check (day_of_week between 1 and 7),

    constraint time_slots_start_hour_check
        check (start_hour between 0 and 23),

    constraint time_slots_end_hour_check
        check (end_hour between 1 and 24),

    constraint time_slots_one_hour_check
        check (end_hour = start_hour + 1),

    constraint time_slots_unique
        unique (day_of_week, start_hour)
);

create table if not exists public.availability (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    user_id bigint not null,
    time_slot_id bigint not null,
    created_at timestamptz not null default now(),

    constraint availability_time_slot_fk
        foreign key (time_slot_id)
        references public.time_slots(id)
        on delete cascade,

    constraint availability_group_member_fk
        foreign key (group_id, user_id)
        references public.group_members(group_id, user_id)
        on delete cascade,

    constraint availability_unique
        unique (group_id, user_id, time_slot_id)
);

-- Seed the 168 weekly one-hour time slots.
-- day_of_week: 1 = Monday, 2 = Tuesday, ..., 7 = Sunday.
insert into public.time_slots (
    day_of_week,
    start_hour,
    end_hour
)
select
    days.day_of_week,
    hours.start_hour,
    hours.start_hour + 1
from generate_series(1, 7) as days(day_of_week)
cross join generate_series(0, 23) as hours(start_hour)
on conflict (day_of_week, start_hour) do nothing;
